name: Deploy

on:
  pull_request_review_comment:
    types:
    - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/deploy-test')
    steps:
    - uses: actions/checkout@v3
