on: issue_comment

jobs:
  commented:
    name: Pull Request comment
    runs-on: ubuntu-latest
    env:
      body: ${{ github.event.comment.body }}
    if: ${{ github.event.issue.pull_request }}
    if: env.body == format('{0}octocat{0} deploy', ':'))
    steps:
    - name: Testing testing
      run: echo "I was run on demand by ${GITHUB_ACTOR}"
