name: Deploy

on:
  issue_comment:
    types:
    - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/deploy-test')
    steps:
    - name: Testing testing
      run: echo "This was triggered by ${GITHUB_ACTOR}."

    - name: Check out the repository code
      uses: actions/checkout@v3
