name: Deploy

on:
  issue_comment:
    types:
    - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Testing testing
      run: echo "I was run on demand by ${GITHUB_ACTOR}"
